2023-04-09 00:33:05,964 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:45]
2023-04-09 00:33:14,757 ERROR: Exception on /reset_password_request [POST] [in /home/keai33/Flask___Mega/microblog/venv/lib/python3.8/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/keai33/Flask___Mega/microblog/venv/lib/python3.8/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/home/keai33/Flask___Mega/microblog/venv/lib/python3.8/site-packages/flask_mail.py", line 427, in send
    connection.send(self)
  File "/home/keai33/Flask___Mega/microblog/venv/lib/python3.8/site-packages/flask_mail.py", line 188, in send
    self.host.sendmail(sanitize_address(envelope_from or message.sender),
  File "/usr/lib/python3.8/smtplib.py", line 865, in sendmail
    self.ehlo_or_helo_if_needed()
  File "/usr/lib/python3.8/smtplib.py", line 604, in ehlo_or_helo_if_needed
    if not (200 <= self.ehlo()[0] <= 299):
  File "/usr/lib/python3.8/smtplib.py", line 444, in ehlo
    self.putcmd(self.ehlo_msg, name or self.local_hostname)
  File "/usr/lib/python3.8/smtplib.py", line 371, in putcmd
    self.send(str)
  File "/usr/lib/python3.8/smtplib.py", line 363, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/keai33/Flask___Mega/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/keai33/Flask___Mega/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/keai33/Flask___Mega/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/keai33/Flask___Mega/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/keai33/Flask___Mega/microblog/app/routes.py", line 185, in reset_password_request
    send_password_reset_email(user)
  File "/home/keai33/Flask___Mega/microblog/app/email.py", line 11, in send_password_reset_email
    send_email('[Microblog] Reset Your Password',
  File "/home/keai33/Flask___Mega/microblog/app/email.py", line 33, in send_email
    mail.send(msg)
  File "/home/keai33/Flask___Mega/microblog/venv/lib/python3.8/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/home/keai33/Flask___Mega/microblog/venv/lib/python3.8/site-packages/flask_mail.py", line 152, in __exit__
    self.host.quit()
  File "/usr/lib/python3.8/smtplib.py", line 997, in quit
    res = self.docmd("quit")
  File "/usr/lib/python3.8/smtplib.py", line 424, in docmd
    self.putcmd(cmd, args)
  File "/usr/lib/python3.8/smtplib.py", line 371, in putcmd
    self.send(str)
  File "/usr/lib/python3.8/smtplib.py", line 363, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
2023-04-09 00:34:02,644 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:45]
2023-04-09 00:37:48,257 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:45]
2023-04-09 00:39:11,918 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:45]
2023-04-09 00:46:58,274 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:45]
2023-04-09 00:53:28,218 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:46]
2023-04-10 01:12:37,438 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:48]
2023-04-10 01:19:39,602 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:48]
2023-04-10 01:32:31,365 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:48]
2023-04-10 01:32:33,344 ERROR: Exception on / [GET] [in /home/keai33/Flask___Mega/microblog/venv/lib/python3.8/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/keai33/Flask___Mega/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/keai33/Flask___Mega/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/keai33/Flask___Mega/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/keai33/Flask___Mega/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/keai33/Flask___Mega/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/keai33/Flask___Mega/microblog/app/routes.py", line 37, in index
    return render_template('index.html', title='Home', form=form,
  File "/home/keai33/Flask___Mega/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/keai33/Flask___Mega/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/home/keai33/Flask___Mega/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/keai33/Flask___Mega/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/keai33/Flask___Mega/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/keai33/Flask___Mega/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/keai33/Flask___Mega/microblog/app/templates/base.html", line 54, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2023-04-10 01:33:30,172 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:48]
2023-04-10 01:57:16,839 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:52]
2023-04-10 02:02:16,067 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:52]
2023-04-10 02:07:05,770 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:52]
2023-04-10 02:07:22,743 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:52]
2023-04-10 02:08:18,878 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:52]
2023-04-10 02:08:50,551 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:52]
2023-04-10 22:52:48,148 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:52]
2023-04-10 22:53:59,619 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:52]
2023-04-10 22:54:31,641 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:52]
2023-04-11 11:56:26,953 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:52]
2023-04-11 11:56:51,938 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:52]
2023-04-11 11:57:20,625 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:52]
2023-04-11 12:17:56,990 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:52]
2023-04-11 12:19:11,476 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:52]
2023-04-11 13:28:53,159 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:52]
2023-04-11 13:29:21,046 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:52]
2023-04-11 13:35:41,370 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:52]
2023-04-11 13:39:57,209 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:52]
2023-04-11 13:44:02,358 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:52]
2023-04-11 13:44:23,798 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:52]
2023-04-11 13:51:41,271 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:52]
2023-04-11 13:58:40,018 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:52]
2023-04-11 13:59:49,474 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:52]
2023-04-11 14:01:20,188 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:52]
2023-04-11 14:01:43,760 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:52]
2023-04-11 14:02:22,883 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:52]
2023-04-11 14:04:19,284 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:52]
2023-04-11 14:04:32,589 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:52]
2023-04-11 14:04:50,442 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:52]
2023-04-11 14:09:42,694 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:52]
2023-04-11 14:10:20,978 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:52]
2023-04-11 14:20:15,435 INFO: Microblog startup [in /home/keai33/Flask___Mega/microblog/app/__init__.py:52]
